development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:608fdf7c2d586d33af126c6b116074df@cod.redistogo.com:11224/
  channel_prefix: chat-app_production
